### ISSUE TITLE
Include this in CAS by default?

### ISSUE THREAD

**Issue by mmoayyed** [stephanarts/cas-integration-zeromq#8]
Hi @stephanarts just wondering, would u be interested to contribute this module to CAS?

**Comment by stephanarts** [comment]
Yes, I would be very happy to change it's license to the CAS license and contribute this module. :)

**Comment by mmoayyed** [comment]
Excellent :) Look forward to the PR.

**Comment by stephanarts** [comment]
Here's a status update of the work involved before submitting the PR.
- [x] Fork cas repository and import code and dependencies
- [x] Refactor code to comply with current checkstyle rules
  **Exception:** _Added JSONRPC as allowed acronym, I felt it was weird to rename that to JsonRpc_
- [x] Use the module name: `cas-server-integration-zeromq`
- [x] Make sure dependencies are all taking the format of `libraries.xyz`
- [ ] Add docs to the `cas-server-documentation`. Follow the same for as the other registries.
- [x] Ensure all transitive dependencies that would produce conflicts are excluded.
- [x] Replace org.json:json with jackson
- [x] Implement Config with standard config framework as is used in the rest of CAS
- [ ] Rewrite unit-tests using spring to make it simmilar to existing CAS unittests.

Added dependencies:
- org.zeromq:jeromq 0.3.5

**Comment by mmoayyed** [comment]
Perfect. Suggestions:
- Use the module name: `cas-server-integration-zeromq`
- Make sure dependencies are all taking the format of `libraries.xyz`
- Add docs to the `cas-server-documentation`. Follow the same for as the other registries.
- Ensure all transitive dependencies that would produce conflicts are excluded.

**Comment by stephanarts** [comment]
https://github.com/stephanarts/cas/tree/cas-integration-zeromq

I am in doubt about how I handled the org.json dependency.

**Comment by mmoayyed** [comment]
You may need to massage the app here to use jackson's JSON support. It would be best if we could avoid duplicate dependencies that provide, more or less, the same functionality.

**Comment by mmoayyed** [comment]
How are we doing here? Making good progress I hope? :) Anything I can do to help?

**Comment by stephanarts** [comment]
i got as far as to get it to compile as part of the cas tree. Porting the unit tests to the way you do unit tests for the rest of cas proved a bit challenging.

I wanted to get the unit tests to work before ripping out the json library and replacing it with something else.

If you would be willing to help out there, I would really appreciate it. 

-----Oorspronkelijk bericht-----
Van: "Misagh Moayyed" notifications@github.com
Verzonden: ‎26-‎5-‎2016 18:16
Aan: "stephanarts/cas-integration-zeromq" cas-integration-zeromq@noreply.github.com
CC: "Stephan Arts" stephan@xfce.org; "Mention" mention@noreply.github.com
Onderwerp: Re: [stephanarts/cas-integration-zeromq] Include this in CAS bydefault? (#8)

How are we doing here? Making good progress I hope? :) Anything I can do to help?

**Comment by mmoayyed** [comment]
Sure. Do you have a branch for me to take a look at?

**Comment by stephanarts** [comment]
https://github.com/stephanarts/cas/tree/cas-integration-zeromq

**Comment by stephanarts** [comment]
I just realised I started putting the unittests in already but forgot to commit. Lemme first get them in the tree and checkstyle-compliant. Then we can have a look at harmonising the setup.

**Comment by mmoayyed** [comment]
Sure

**Comment by stephanarts** [comment]
@mmoayyed 
I have put all the unittests in (I think), but they don't seem to be executed. Could you take a look at what I've done wrong?

**Comment by mmoayyed** [comment]
Sure. I'll try to get to this later this evening.

**Comment by mmoayyed** [comment]
Your test class names must end with Tests. 

Also sync with master once.

**Comment by stephanarts** [comment]
Thanks, I now know where to continue :)

**Comment by stephanarts** [comment]
Status-update:
I've synced with master, changed the namespace and replaced org.json with jackson.

I'm now working on getting the unit-tests to pass again.

**Comment by mmoayyed** [comment]
How's it going here? Need help?

**Comment by stephanarts** [comment]
I had some problems getting to grips with using the spring configuration context for the unit-tests.
The basic method related unit-tests now pass. I'm now down to the more high-level tests.

stephanarts/cas@4f7f0da57912ca1b1e903a76f177b3854d916864

If you have any suggestions about how to handle the 'destruction' and 'reuse' of the context, I would love that. I never was too happy that I used a dozen TCP ports for the purpose of the unittests. If you have some ideas on how to improve that.

**Comment by stephanarts** [comment]
I am now a bit at a loss how the spring autowiring works. 

More precise; the error it gives:
`Could not autowire field: private boolean org.apereo.cas.ticket.registry.AbstractTicketRegistry.cleanerEnabled`

If you could take a look and point me in the right direction that would help a lot.

**Comment by mmoayyed** [comment]
Sure. Hang tight.

**Comment by mmoayyed** [comment]
I am going to try and review your changes here this week. I notice that you are using 4.2.x. For this to be included in CAS, you really should be on 5.x which is in SNAPSHOT mode. The PR I will probably present to you will be based on 5 as well. So let's start there.
